# Change these first
owner: privacytime101 # Your GitHub organization or username, where this repository lives
repo: PipedStatus # The name of this repository
assignees: 
  - privacytime101
  - httpjamesm
user-agent: privacytime101

sites:
  - name: Google
    url: https://www.google.com
    expectedStatusCodes:
      - 200
      - 201
  - name: Kavin Instance
    url: https://piped.kavin.rocks
    expectedStatusCodes:
      - 200
      - 201

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: piped.faith
  # baseUrl: /your-repo-name
  logoUrl: https://watch.whatever.social/favicon.ico
  themeUrl: https://cdn.statically.io/gh/privacytime101/PipedStatus/master/assets/custom.css
  name: Piped Status
  introTitle: "Piped Status"
  introMessage: "See what's happening in the Pipedverse. Maintained by whatever.social and horizon.pics, powered by Upptime."
  navbar:
    - title: Piped Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
